### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [LastGenius-edu/homeworks_project#2]
Опис даних дуже короткий - Вказати формат, структуру згідно з форматом та відповідні до структури всі елементи.
Прочитайте про корпуси текстів, бо виглядає що Ви хочете робити щось що їх сильно нагадує https://langsci-press.org/catalog/book/148

**Comment by last-genius** [comment]
Чи достатньо такого опису структури? https://github.com/LastGenius-edu/homeworks_project/wiki/3.-Домашнє-завдання-№2

Про корпуси дещо знаю, NLTK має навіть один невеликий з книг Project Gutenberg (всього 18 томів), але я намагаюсь не розпізнати і натренуватись на мові в цілому, а прослідкувати її розвиток на прикладі великої кількості книг з різних періодів.

**Comment by anrom7** [comment]
Отже, це diachronic corpora - історичні корпуси. https://www.lancaster.ac.uk/fass/projects/corpus/ZJU/xCBLS/chapters/A07.pdf
http://martinweisser.org/corpora_site/historical_corpora.html
https://www.ninjal.ac.jp/english/research/project-3/institute/diachronic-corpora/ 
https://ids-pub.bsz-bw.de/frontdoor/index/index/year/2016/docId/4890
