### ISSUE TITLE
ДЗ4

### ISSUE THREAD

**Issue by anrom7** [LastGenius-edu/homeworks_project#3]
Не знаю чи Ви десь згадуєте що  __dispersion_graph це ідея з nltk (модуль dispersion.py з пакунка nltk.draw). Вартує це вказати.

**Comment by last-genius** [comment]
Так, просто прийшлося трохи переписати їх source-code, він не дозволяв багато кастомізації. Сама побудова графіків заснована на matplotlib (pylab)
